export const SETTING_RIGHT_DRAWER_UPEN = "SETTING_RIGHT_DRAWER_UPEN";
export const SETTING_RIGHT_DRAWER_CLOSE = "SETTING_RIGHT_DRAWER_CLOSE";

export const IMAGE_SECOND_DRAWER_OPEN = "SETTING_RIGHT_DRAWER_OPEN";
export const IMAGE_SECOND_DRAWER_CLOSE = "SETTING_RIGHT_DRAWER_CLOSE";

export const ENABLE_EDITOR = "ENABLE_EDITOR";
export const DISABLE_EDITOR = "DISABLE_EDITOR";

export const CODE_DRAWER_OPEN = "CODE_DRAWER_OPEN"; 
export const CODE_DRAWER_CLOSE = "CODE_DRAWER_CLOSE";

export const CODE= "CODE";